"""Refresh _MISSING_PERMITS.md — store × permit gap report with real expiry dates."""

from __future__ import annotations

import csv
import json
import re
import sys
from collections import defaultdict
from datetime import date, datetime
from pathlib import Path
from typing import Optional

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

REPO_ROOT = Path(__file__).resolve().parents[2]
MD_ROOT = REPO_ROOT / "data" / "admin_markdown"
REGISTRY_CSV = REPO_ROOT / "data" / "admin_drive_audit" / "company_registry.csv"
OUT_MD = MD_ROOT / "_MISSING_PERMITS.md"

REQUIRED_CORP_PERMITS = ["BIR_2303", "SEC_AOI", "SEC_BYLAWS", "SEC_GIS"]
REQUIRED_STORE_PERMITS = ["BIR_2303", "BP", "BARANGAY_CLEARANCE", "FSIC", "SANITARY", "DOLE"]


def _parse_yaml_value(raw: str):
    raw = raw.strip()
    if raw in {"", "null", "~"}: return None
    if raw.startswith(('"', "[", "{")):
        try: return json.loads(raw)
        except json.JSONDecodeError: return raw.strip('"')
    try: return float(raw) if "." in raw else int(raw)
    except ValueError: return raw


def _parse_frontmatter(text: str) -> dict:
    if not text.startswith("---"): return {}
    parts = text.split("---", 2)
    if len(parts) < 3: return {}
    out: dict = {}
    for line in parts[1].splitlines():
        if not line.strip() or line.startswith("#"): continue
        m = re.match(r"^([A-Za-z0-9_]+):\s?(.*)$", line)
        if m: out[m.group(1)] = _parse_yaml_value(m.group(2))
    return out


def _parse_date(s):
    if not s: return None
    s = str(s).strip()
    for fmt in ("%Y-%m-%d", "%Y/%m/%d", "%m/%d/%Y", "%d/%m/%Y"):
        try: return datetime.strptime(s, fmt).date()
        except ValueError: continue
    try: return date.fromisoformat(s[:10])
    except ValueError: return None


def _cell_for(docs):
    if not docs: return "❌"
    today = date.today()
    latest_exp = None
    any_expired = False
    any_soon = False
    for d in docs:
        ex = _parse_date(str(d.get("canonical_expiry_date") or ""))
        if not ex: continue
        if latest_exp is None or ex > latest_exp: latest_exp = ex
        if ex < today: any_expired = True
        elif (ex - today).days <= 90: any_soon = True
    if latest_exp is None:
        return f"✅ (no expiry) ×{len(docs)}"
    if any_expired and latest_exp < today: return f"⚠️ {latest_exp.isoformat()} EXPIRED"
    if any_soon: return f"⚠️ {latest_exp.isoformat()} soon"
    return f"✅ {latest_exp.isoformat()}"


def main():
    stores = []
    corps = []
    if REGISTRY_CSV.exists():
        with REGISTRY_CSV.open("r", encoding="utf-8-sig") as fh:
            for row in csv.DictReader(fh):
                cat = (row.get("entity_category") or "").strip().lower()
                if cat == "store": stores.append(row)
                else: corps.append(row)

    by_ep = defaultdict(list)
    for p in MD_ROOT.rglob("*.md"):
        if p.name.startswith("_") or "_staging" in p.parts or "_validation" in p.parts:
            continue
        fm = _parse_frontmatter(p.read_text(encoding="utf-8"))
        if not fm: continue
        by_ep[(fm.get("entity_code") or "UNKNOWN", fm.get("permit_code") or "UNKNOWN")].append(fm)

    lines = [
        "# BEI Admin – Missing Permits + Expiry Gap Report", "",
        "Generated by `scripts/admin_markdown_pipeline/22_build_gap_report.py`.", "",
        "Legend: ✅ on file + valid, ⚠️ on file but expired / near-expiry, ❌ not on file.", "",
    ]
    lines.extend(["## Corporate-level permits", "", "| Entity | BIR 2303 | SEC AOI | SEC BYLAWS | SEC GIS |", "|---|---|---|---|---|"])
    for corp in sorted(corps, key=lambda r: r.get("abbr") or r.get("corp_suffix") or ""):
        key = f"CORP_{(corp.get('abbr') or corp.get('corp_suffix') or '').strip().upper()}"
        row = [corp.get("full_company_name") or corp.get("corp_suffix") or key]
        for permit in REQUIRED_CORP_PERMITS: row.append(_cell_for(by_ep.get((key, permit), [])))
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")

    lines.extend(["## Store-level permits", "", "| Store | Corp | BIR 2303 | BP | BARANGAY | FSIC | SANITARY | DOLE |", "|---|---|---|---|---|---|---|---|"])
    for store in sorted(stores, key=lambda r: r.get("store_prefix") or ""):
        corp = store.get("corp_suffix") or ""
        prefix = store.get("store_prefix") or ""
        abbr = store.get("abbr") or ""
        candidates = [f"STORE_{abbr.upper()}", f"STORE_{re.sub(r'[^A-Za-z0-9]', '', prefix).upper()}", f"CORP_{abbr.upper()}"]
        row = [prefix or abbr, corp]
        for permit in REQUIRED_STORE_PERMITS:
            docs = []
            for ent in candidates: docs.extend(by_ep.get((ent, permit), []))
            row.append(_cell_for(docs))
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")

    total = sum(len(v) for v in by_ep.values())
    lines.append(f"Total admin MD files indexed: **{total}**.")
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_MD.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
