
import unittest
import pandas as pd
import io
import sys
import os

# Add project root to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from hrms.utils.pos_parser import parse_sales_summary, parse_transaction_report

class TestPOSParser(unittest.TestCase):

    def create_mock_sales_summary(self):
        # Create a DataFrame that mimics the Sales Summary format
        # Rows 0-7: Metadata
        # Row 9: Header
        # Row 10: Data
        
        data = [
            ["POS: Mosaic POS v1.5", "POS: Mosaic POS v1.5"],
            ["Account Name:", "BEBANG"],
            ["Location:", "Test Location"],
            ["TIN:", "123-456-789"],
            ["From Date:", "2026-02-18"],
            ["To Date:", "2026-02-18"],
            ["Generated Date:", "2026-02-19"],
            ["Generated by:", "Tester"],
            [], # Row 8 empty
            ["Date", "MIN", "Invoice From", "Invoice To", "Beg Balance", "End Balance", "Net Sales", "Gross Sales", "Vatable", "VAT", "Exempt", "Zero Rated", "Del Fee", "Other Income", "GC Excess", "Disc PWD", "Disc Senior", "Disc Other", "VAT Adj", "Overrun", "Returns", "Void", "EOD Counter", "Remarks"],
            ["2026-02-18", "MIN123", 1001, 1050, 0, 0, 4464.29, 5000.00, 4464.29, 535.71, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, ""]
        ]
        
        df = pd.DataFrame(data)
        
        # Convert to bytes
        output = io.BytesIO()
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            df.to_excel(writer, index=False, header=False)
        return output.getvalue()

    def create_mock_transaction_report(self):
        # Create a DataFrame for Transaction Report
        # Row 0: Header
        data = {
            "Bill #": [1, 2, 3],
            "Receipt #": [1001, 1002, 1003],
            "Location": ["Loc1", "Loc1", "Loc1"],
            "Status": ["Paid", "Paid", "Paid"],
            "Service Type": ["Dine In", "Take Out", "Dine In"],
            "Service Channel": ["Store", "Store", "Store"],
            "Payment Type": ["Cash", "Card", "Cash"],
            "Guest Count": [1, 2, 1],
            "Tax": [10.0, 20.0, 10.0],
            "Sub-total": [100.0, 200.0, 100.0],
            "Total": [110.0, 220.0, 110.0],
            "Gross Sales": [110.0, 220.0, 110.0],
            "Date": ["2026-02-18", "2026-02-18", "2026-02-18"]
        }
        df = pd.DataFrame(data)
        
        output = io.BytesIO()
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            df.to_excel(writer, index=False)
        return output.getvalue()

    def test_sales_summary_parsing(self):
        content = self.create_mock_sales_summary()
        result = parse_sales_summary(content)
        
        self.assertTrue(result['success'])
        self.assertEqual(result['summary']['gross_sales'], 5000.00)
        self.assertEqual(result['summary']['net_sales'], 4464.29)
        self.assertEqual(result['summary']['transaction_count'], 49) # 1050 - 1001
        self.assertEqual(result['metadata']['account_name'], "BEBANG")

    def test_transaction_report_parsing(self):
        content = self.create_mock_transaction_report()
        result = parse_transaction_report(content)
        
        self.assertTrue(result['success'])
        self.assertEqual(result['totals']['gross_sales'], 440.0)
        self.assertEqual(result['totals']['by_payment_type']['Cash'], 220.0) # 110 + 110
        self.assertEqual(result['totals']['by_payment_type']['Card'], 220.0)

    def test_broken_format_handling(self):
        # Test with empty/garbage file
        result = parse_sales_summary(b"garbage data")
        self.assertFalse(result['success'])

if __name__ == '__main__':
    unittest.main()
