import sys
import unittest
from unittest.mock import MagicMock, patch
import pandas as pd
import io
import os

# Manual Mock Construction
frappe_mock = MagicMock()
sys.modules['frappe'] = frappe_mock
sys.modules['frappe.model'] = MagicMock()
sys.modules['frappe.model.workflow'] = MagicMock()
sys.modules['frappe.utils'] = MagicMock()
sys.modules['frappe.utils.data'] = MagicMock()
sys.modules['frappe.query_builder'] = MagicMock()
sys.modules['frappe.rate_limiter'] = MagicMock()
sys.modules['erpnext'] = MagicMock()
sys.modules['erpnext.setup'] = MagicMock()
sys.modules['erpnext.setup.doctype'] = MagicMock()
sys.modules['erpnext.setup.doctype.employee'] = MagicMock()
sys.modules['erpnext.setup.doctype.employee.employee'] = MagicMock()
sys.modules['PIL'] = MagicMock()
sys.modules['boto3'] = MagicMock()

# Add project root to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from hrms.utils.pos_parser import parse_sales_summary

class TestPOSParser(unittest.TestCase):

    def _create_mock_dataframe(self, shift_rows=0):
        # Create data structure mimicking Z-Reading
        # Rows 0-7: Metadata
        metadata = [
            ["POS: Mosaic POS v1.5", ""],
            ["Account Name:", "BEBANG"],
            ["Location:", "Test Location"],
            ["TIN:", "123-456-789"],
            ["From Date:", "2026-02-18"],
            ["To Date:", "2026-02-18"],
            ["Generated Date:", "2026-02-19"],
            ["Generated by:", "Tester"]
        ]
        
        # Shift rows if requested (to test brittleness)
        prefix = [["Shifted", ""]] * shift_rows
        
        # Row 9 (or 9+shift): Header
        # Row 10 (or 10+shift): Data
        padding = [["", ""]] 
        
        header = ["Date", "MIN", "Invoice From", "Invoice To", "Beg Balance", "End Balance", "Net Sales", "Gross Sales", "Vatable", "VAT", "Exempt", "Zero Rated", "Del Fee", "Other Income", "GC Excess", "Disc PWD", "Disc Senior", "Disc Other", "VAT Adj", "Overrun", "Returns", "Void", "EOD Counter", "Remarks"]
        
        data_row = ["2026-02-18", "MIN123", 1001, 1050, 0, 0, 4464.29, 5000.00, 4464.29, 535.71, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, ""]
        
        all_rows = prefix + metadata + padding + [header] + [data_row]
        
        return pd.DataFrame(all_rows)

    @patch('hrms.utils.pos_parser.pd.read_excel')
    def test_sales_summary_parsing_success(self, mock_read_excel):
        print("\n[TEST] Normal Sales Summary Parsing")
        
        # Setup mock to return our DataFrame
        mock_df = self._create_mock_dataframe(shift_rows=0)
        mock_read_excel.return_value = mock_df
        
        result = parse_sales_summary(b"dummy_content")
        
        if not result['success']:
            print(f"Parsing failed: {result.get('error')}")

        self.assertTrue(result['success'])
        self.assertEqual(result['summary']['gross_sales'], 5000.00)
        print(" -> Success: Gross Sales = 5000.00")

    @patch('hrms.utils.pos_parser.pd.read_excel')
    def test_brittle_parsing_shifted_rows(self, mock_read_excel):
        print("\n[TEST] Brittle Parsing (Shifted by 1 row)")
        
        # Setup mock to return shifted DataFrame
        mock_df = self._create_mock_dataframe(shift_rows=1)
        mock_read_excel.return_value = mock_df
        
        result = parse_sales_summary(b"dummy_content")
        
        # The test expects 0.0 because of the brittleness
        self.assertTrue(result['success']) 
        self.assertEqual(result['summary']['gross_sales'], 0.0)
        print(" -> Confirmed: Gross Sales = 0.0 (Expected 5000.00). Parser is brittle.")

if __name__ == '__main__':
    unittest.main()
