#!/usr/bin/env python3
"""S247 Phase 3C.4 — install `bki_si_reference` Custom Field on Stock Entry.

Idempotent: skips if the field already exists. Runs AFTER PR merge + deploy +
`bench migrate` (which adds the BEI Settings toggle fields from doctype JSON).

Wraps `frappe.custom_field.create_custom_field`. Mirrors the PI generator's
`bki_si_reference` Custom Field on Purchase Invoice.
"""
from __future__ import annotations

import os
for d in [
    "/home/frappe/logs",
    "/home/frappe/frappe-bench/logs",
    "/home/frappe/frappe-bench/hq.bebang.ph/logs",
    "/home/frappe/frappe-bench/sites/hq.bebang.ph/logs",
]:
    os.makedirs(d, exist_ok=True)

import json
import sys
from datetime import datetime

import frappe  # type: ignore
from frappe.custom.doctype.custom_field.custom_field import create_custom_field


def main() -> None:
    payload = {
        "sprint": "S247",
        "phase": "3C.4",
        "purpose": "install bki_si_reference Custom Field on Stock Entry",
        "timestamp_utc": datetime.utcnow().isoformat() + "Z",
    }
    try:
        frappe.init(site="hq.bebang.ph", sites_path="/home/frappe/frappe-bench/sites")
        frappe.connect()
        frappe.set_user("Administrator")

        # Idempotency: check both DocType meta + Custom Field row
        if frappe.get_meta("Stock Entry").has_field("bki_si_reference"):
            payload["status"] = "ALREADY_INSTALLED"
            payload["existing_field"] = "Stock Entry.bki_si_reference"
        else:
            create_custom_field("Stock Entry", {
                "fieldname": "bki_si_reference",
                "label": "BKI SI Reference",
                "fieldtype": "Link",
                "options": "Sales Invoice",
                "read_only": 1,
                "insert_after": "stock_entry_type",
                "description": (
                    "S247: link from a Stock Entry (Material Receipt) generated by the "
                    "BKI->Store flow back to the originating BKI Sales Invoice. Set by "
                    "hrms.api.bki_store_stock_entry_generator.maybe_generate_store_stock_entry."
                ),
                "in_list_view": 0,
                "in_standard_filter": 1,
                "translatable": 0,
            })
            frappe.db.commit()
            payload["status"] = "INSTALLED"
            payload["installed_field"] = "Stock Entry.bki_si_reference"

        # Verify post-install
        payload["post_install_has_field"] = frappe.get_meta("Stock Entry").has_field(
            "bki_si_reference"
        )
        # Also check the new BEI Settings toggles came across from bench migrate
        payload["post_install_settings_toggles"] = {
            "enable_bki_store_pi_generator_field_exists": frappe.get_meta("BEI Settings").has_field(
                "enable_bki_store_pi_generator"
            ),
            "enable_bki_store_stock_entry_generator_field_exists": frappe.get_meta(
                "BEI Settings"
            ).has_field("enable_bki_store_stock_entry_generator"),
        }

    except Exception as e:
        import traceback
        payload["status"] = "ERROR"
        payload["fatal_error"] = str(e)
        payload["traceback"] = traceback.format_exc()

    out_path = "/tmp/s247_se_install.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, default=str)
    sys.stdout.write(f"S247_SE_INSTALL_OK status={payload.get('status')}\n")
    sys.stdout.flush()


if __name__ == "__main__":
    main()
