#!/usr/bin/env python3
"""
Split legacy docs/testing/TEST_SCENARIOS.md into modular scenario files.

This keeps the historical monolith intact while creating a maintainable
docs/testing/scenarios/* catalog used by l3-v2.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
LEGACY_FILE = ROOT / "docs" / "testing" / "TEST_SCENARIOS.md"
SCENARIO_ROOT = ROOT / "docs" / "testing" / "scenarios"

SECTION_FILE_MAP = {
    "How Scenarios Work": "COMMON.md",
    "Maintenance Module (15 scenarios)": "modules/maintenance.md",
    "Store Operations Module (10 scenarios)": "modules/store-operations.md",
    "HR Self-Service Module (8 scenarios + 2 bug regression)": "modules/hr-self-service.md",
    "Expense Module (6 scenarios)": "modules/expense.md",
    "Communication Module (4 scenarios)": "modules/communication.md",
    "Regression Bank": "regressions/regression-bank.md",
    "Finance & Billing": "modules/finance-and-billing.md",
    "Biometric Monitoring Module (14 scenarios)": "modules/biometric-monitoring.md",
    "Billing Module (17 scenarios)": "modules/billing.md",
    "SCM & Logistics Module (14 scenarios)": "modules/scm-logistics.md",
    "Store Ops + Inventory Sprint Scenarios (21 scenarios)": "modules/store-ops-inventory-sprint.md",
    "Regression Bank Updates (Store Ops + Inventory Sprint)": "regressions/regression-bank-store-ops-inventory.md",
}


def _section_spans(text: str) -> list[tuple[str, int, int]]:
    headings = list(re.finditer(r"^##\s+(.+)$", text, flags=re.M))
    spans: list[tuple[str, int, int]] = []
    for idx, match in enumerate(headings):
        title = match.group(1).strip()
        start = match.end()
        end = headings[idx + 1].start() if idx + 1 < len(headings) else len(text)
        spans.append((title, start, end))
    return spans


def _extract_sections(text: str) -> tuple[str, dict[str, str]]:
    spans = _section_spans(text)
    if not spans:
        return text.strip(), {}

    first_h2 = re.search(r"^##\s+.+$", text, flags=re.M)
    preface = text[: first_h2.start()].strip() if first_h2 else text.strip()
    section_map: dict[str, str] = {}
    for title, start, end in spans:
        section_map[title] = text[start:end].strip()
    return preface, section_map


def _normalize_title(raw: str) -> str:
    title = re.sub(r"\s+\([^)]*\)$", "", raw).strip()
    title = title.replace("&", "and")
    return title


def _write(relative_path: str, title: str, content: str) -> None:
    target = SCENARIO_ROOT / relative_path
    target.parent.mkdir(parents=True, exist_ok=True)
    payload = (
        f"# {title}\n\n"
        "<!-- Generated by scripts/testing/build_l3_scenario_catalog.py from "
        "docs/testing/TEST_SCENARIOS.md -->\n\n"
        f"{content.rstrip()}\n"
    )
    target.write_text(payload, encoding="utf-8")


def _extract_procure_to_pay(text: str) -> str:
    blocks: list[str] = []
    markers = list(re.finditer(r"^###\s+(T-PROC-\d{3}:.+)$", text, flags=re.M))
    for idx, marker in enumerate(markers):
        start = marker.start()
        end = markers[idx + 1].start() if idx + 1 < len(markers) else len(text)
        blocks.append(text[start:end].strip())
    return "\n\n---\n\n".join(blocks).strip()


def _trim_procure_to_pay_from_sprint_section(content: str) -> str:
    match = re.search(r"^###\s+T-PROC-\d{3}:", content, flags=re.M)
    if not match:
        return content
    return content[: match.start()].rstrip()


def main() -> int:
    if not LEGACY_FILE.exists():
        raise SystemExit(f"Missing legacy source: {LEGACY_FILE}")

    text = LEGACY_FILE.read_text(encoding="utf-8")
    preface, sections = _extract_sections(text)

    common_section = sections.get("How Scenarios Work", "")
    _write(
        "COMMON.md",
        "L3 Scenario Common Rules",
        f"{preface}\n\n## How Scenarios Work\n\n{common_section}".strip(),
    )

    for heading, rel_path in SECTION_FILE_MAP.items():
        if heading == "How Scenarios Work":
            continue
        content = sections.get(heading, "").strip()
        if not content:
            continue
        if heading == "Store Ops + Inventory Sprint Scenarios (21 scenarios)":
            content = _trim_procure_to_pay_from_sprint_section(content)
        _write(rel_path, _normalize_title(heading), content)

    procure_to_pay = _extract_procure_to_pay(text)
    if procure_to_pay:
        _write(
            "flows/procure-to-pay.md",
            "Procure To Pay Flow",
            (
                "This flow file is extracted from the legacy scenario registry.\n\n"
                f"{procure_to_pay}"
            ),
        )

    # Placeholder flow file for missing domains found in the V2 plan.
    hire_flow = SCENARIO_ROOT / "flows" / "hire-to-onboard.md"
    hire_flow.parent.mkdir(parents=True, exist_ok=True)
    hire_flow.write_text(
        (
            "# Hire To Onboard Flow\n\n"
            "<!-- Maintained manually. Add executable scenarios before marking ready. -->\n\n"
            "Status: `gap`\n\n"
            "Planned coverage:\n"
            "- recruitment\n"
            "- onboarding\n"
            "- employee_clearance\n"
            "- boarding_status completion\n"
        ),
        encoding="utf-8",
    )

    commissary_flow = SCENARIO_ROOT / "flows" / "dispatch-warehouse-commissary.md"
    commissary_flow.write_text(
        (
            "# Dispatch Warehouse Commissary Flow\n\n"
            "<!-- Maintained manually. Add commissary-specific executable scenarios. -->\n\n"
            "Status: `partial`\n\n"
            "Current executable coverage lives in:\n"
            "- modules/scm-logistics.md\n\n"
            "Missing executable coverage:\n"
            "- commissary endpoint namespace and workflows\n"
        ),
        encoding="utf-8",
    )

    print("Built modular L3 scenario catalog under docs/testing/scenarios/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
