# Copyright (c) 2026, Frappe Technologies Pvt. Ltd. and contributors
# For license information, please see license.txt

"""
POS File Parser for MOSAIC POS System

Parses 5 export file types from MOSAIC POS:
1. Sales Summary - Z-Reading equivalent (invoice numbers, totals, discounts)
2. Transaction Report - Per-transaction detail
3. Discount Report - SC/PWD and promo discount breakdown
4. Daily Sales Revenue - Per-transaction revenue with payment types
5. Product Mix - SKU-level sales for BOM deduction

All parsers return structured dictionaries that can be used for:
- Auto-populating closing report fields
- Cross-validating against OCR-extracted Z-Reading data
- Inventory BOM deduction calculations
"""

import io
import pandas as pd
from datetime import datetime
from typing import Optional, Dict, Any, List, Tuple


# ==============================================================================
# COMMON UTILITIES
# ==============================================================================

def _extract_metadata(df: pd.DataFrame) -> Dict[str, Any]:
    """
    Extract common metadata from MOSAIC header rows.
    Header format (rows 0-7):
        0: POS: Mosaic POS v1.5
        1: Account Name: BEBANG
        2: Location: [Full address]
        3: TIN: 649154841-00001
        4: From Date: 2026-01-30
        5: To Date: 2026-01-30
        6: Generated Date: 2026-01-31
        7: Generated by: [username]
    """
    metadata = {}
    try:
        metadata["pos_version"] = str(df.iloc[0, 1]) if pd.notna(df.iloc[0, 1]) else None
        metadata["account_name"] = str(df.iloc[1, 1]) if pd.notna(df.iloc[1, 1]) else None
        metadata["location"] = str(df.iloc[2, 1]) if pd.notna(df.iloc[2, 1]) else None
        metadata["tin"] = str(df.iloc[3, 1]) if pd.notna(df.iloc[3, 1]) else None

        # Parse dates
        from_date = df.iloc[4, 1]
        to_date = df.iloc[5, 1]
        generated_date = df.iloc[6, 1]

        if pd.notna(from_date):
            metadata["from_date"] = _parse_date(from_date)
        if pd.notna(to_date):
            metadata["to_date"] = _parse_date(to_date)
        if pd.notna(generated_date):
            metadata["generated_date"] = _parse_date(generated_date)

        metadata["generated_by"] = str(df.iloc[7, 1]) if pd.notna(df.iloc[7, 1]) else None
    except Exception:
        pass

    return metadata


def _parse_date(value) -> Optional[str]:
    """Parse various date formats to YYYY-MM-DD string."""
    if pd.isna(value):
        return None

    if isinstance(value, datetime):
        return value.strftime("%Y-%m-%d")

    if isinstance(value, str):
        # Try common formats
        for fmt in ["%Y-%m-%d", "%b-%d-%Y", "%d-%b-%Y", "%m/%d/%Y", "%d/%m/%Y"]:
            try:
                return datetime.strptime(value, fmt).strftime("%Y-%m-%d")
            except ValueError:
                continue

    return str(value) if value else None


def _safe_float(value, default: float = 0.0) -> float:
    """Safely convert value to float, handling comma-formatted numbers."""
    if pd.isna(value):
        return default
    try:
        if isinstance(value, str):
            # Remove commas and handle accounting format (parentheses for negatives)
            cleaned = value.replace(",", "").strip()
            if cleaned.startswith("(") and cleaned.endswith(")"):
                cleaned = "-" + cleaned[1:-1]
            return float(cleaned)
        return float(value)
    except (ValueError, TypeError):
        return default


def _safe_int(value, default: int = 0) -> int:
    """Safely convert value to int, handling comma-formatted numbers."""
    if pd.isna(value):
        return default
    try:
        if isinstance(value, str):
            # Remove commas
            cleaned = value.replace(",", "").strip()
            return int(float(cleaned))
        return int(float(value))
    except (ValueError, TypeError):
        return default


# ==============================================================================
# SALES SUMMARY PARSER (Z-Reading Equivalent)
# ==============================================================================

def parse_sales_summary(file_content: bytes) -> Dict[str, Any]:
    """
    Parse MOSAIC Sales Summary export.

    This is the Z-Reading equivalent containing:
    - Invoice number range (Beginning SI to Ending SI)
    - Gross/Net sales totals
    - VAT breakdown
    - Discount totals by type
    - Transaction count (EOD Counter)

    Args:
        file_content: Excel file bytes

    Returns:
        Dictionary with extracted data:
        {
            "metadata": {...},
            "summary": {
                "date": "2026-01-30",
                "beginning_si": 45788,
                "ending_si": 46000,
                "eod_counter": 213,
                "gross_sales": 68562.00,
                "net_sales": 58114.11,
                "vatable_sales": 51825.00,
                "vat": 5585.26,
                "vat_exempt_sales": 1234.00,
                "zero_rated_sales": 0.00,
                "discount_pwd": 500.00,
                "discount_senior": 750.00,
                "discount_other": 100.00,
                "vat_adjustment": 150.00,
                "delivery_fee": 0.00,
                "other_income": 0.00,
                "gc_excess": 0.00,
                "returns": 0.00,
                "void_count": 0
            },
            "success": True
        }
    """
    try:
        df = pd.read_excel(io.BytesIO(file_content), header=None)
        metadata = _extract_metadata(df)

        # Find header row (row 9 in standard format)
        header_row = 9
        data_row = 10

        # Map column names
        # Standard columns: Date, MIN, Invoice Number From, Invoice Number To,
        # Beginning Balance, Ending Balance, Net Sales, Gross Sales, VATABLE Sales,
        # VAT, VAT Exempt Sales, Zero Rated Sales, Delivery Fee, Other Income,
        # Gc Excess, Discount Pwd, Discount Senior, Discount Other, Vat Adjustment,
        # Sales Overrun Amount, Returns, Void, EOD Counter, Remarks

        # Get data row
        if len(df) > data_row:
            row = df.iloc[data_row]

            summary = {
                "date": _parse_date(row.iloc[0]),
                "min": str(row.iloc[1]) if pd.notna(row.iloc[1]) else None,
                "beginning_si": _safe_int(row.iloc[2]),
                "ending_si": _safe_int(row.iloc[3]),
                "beginning_balance": _safe_float(row.iloc[4]),
                "ending_balance": _safe_float(row.iloc[5]),
                "net_sales": _safe_float(row.iloc[6]),
                "gross_sales": _safe_float(row.iloc[7]),
                "vatable_sales": _safe_float(row.iloc[8]),
                "vat": _safe_float(row.iloc[9]),
                "vat_exempt_sales": _safe_float(row.iloc[10]),
                "zero_rated_sales": _safe_float(row.iloc[11]),
                "delivery_fee": _safe_float(row.iloc[12]),
                "other_income": _safe_float(row.iloc[13]),
                "gc_excess": _safe_float(row.iloc[14]),
                "discount_pwd": _safe_float(row.iloc[15]),
                "discount_senior": _safe_float(row.iloc[16]),
                "discount_other": _safe_float(row.iloc[17]),
                "vat_adjustment": _safe_float(row.iloc[18]),
                "sales_overrun": _safe_float(row.iloc[19]),
                "returns": _safe_float(row.iloc[20]),
                "void_count": _safe_int(row.iloc[21]),
                "eod_counter": _safe_int(row.iloc[22]),
            }

            # Calculate transaction count
            if summary["beginning_si"] and summary["ending_si"]:
                summary["transaction_count"] = summary["ending_si"] - summary["beginning_si"]

            return {
                "metadata": metadata,
                "summary": summary,
                "success": True
            }

        return {"success": False, "error": "No data row found"}

    except Exception as e:
        return {"success": False, "error": str(e)}


# ==============================================================================
# TRANSACTION REPORT PARSER
# ==============================================================================

def parse_transaction_report(file_content: bytes) -> Dict[str, Any]:
    """
    Parse MOSAIC Transaction Report export.

    Contains per-transaction details:
    - Bill/Receipt numbers
    - Payment types (Cash, GCash, Card, etc.)
    - Service type (Pickup, Delivery)
    - Tax and totals per transaction

    Args:
        file_content: Excel file bytes

    Returns:
        Dictionary with extracted data:
        {
            "transactions": [...],
            "totals": {
                "gross_sales": 12345.00,
                "net_sales": 11000.00,
                "tax_total": 1200.00,
                "transaction_count": 50,
                "by_payment_type": {
                    "Cash": 5000.00,
                    "GCash": 3000.00,
                    ...
                }
            },
            "success": True
        }
    """
    try:
        df = pd.read_excel(io.BytesIO(file_content), header=0)

        # Clean column names
        df.columns = df.columns.str.strip()

        transactions = []
        payment_totals = {}
        gross_total = 0.0
        tax_total = 0.0

        for _, row in df.iterrows():
            # Skip summary rows
            if pd.isna(row.get("Bill #")):
                continue

            tx = {
                "bill_no": _safe_int(row.get("Bill #")),
                "receipt_no": _safe_int(row.get("Receipt #")),
                "location": str(row.get("Location", "")) if pd.notna(row.get("Location")) else None,
                "status": str(row.get("Status", "")) if pd.notna(row.get("Status")) else None,
                "service_type": str(row.get("Service Type", "")) if pd.notna(row.get("Service Type")) else None,
                "service_channel": str(row.get("Service Channel", "")) if pd.notna(row.get("Service Channel")) else None,
                "payment_type": str(row.get("Payment Type", "")) if pd.notna(row.get("Payment Type")) else None,
                "guest_count": _safe_int(row.get("Guest Count", 1)),
                "tax": _safe_float(row.get("Tax")),
                "subtotal": _safe_float(row.get("Sub-total")),
                "total": _safe_float(row.get("Total")),
                "gross_sales": _safe_float(row.get("Gross Sales")),
                "date": _parse_date(row.get("Date")),
            }

            transactions.append(tx)

            # Accumulate totals
            gross_total += tx["gross_sales"]
            tax_total += tx["tax"]

            payment_type = tx["payment_type"] or "Unknown"
            if payment_type not in payment_totals:
                payment_totals[payment_type] = 0.0
            payment_totals[payment_type] += tx["total"]

        return {
            "transactions": transactions,
            "totals": {
                "gross_sales": gross_total,
                "tax_total": tax_total,
                "transaction_count": len(transactions),
                "by_payment_type": payment_totals
            },
            "success": True
        }

    except Exception as e:
        return {"success": False, "error": str(e)}


# ==============================================================================
# DISCOUNT REPORT PARSER
# ==============================================================================

def parse_discount_report(file_content: bytes) -> Dict[str, Any]:
    """
    Parse MOSAIC Discount Report export.

    Contains discount breakdown by type:
    - SC (Senior Citizen)
    - PWD
    - Promo discounts
    - VAT adjustments

    Args:
        file_content: Excel file bytes

    Returns:
        Dictionary with extracted data:
        {
            "metadata": {...},
            "discounts": [...],
            "totals": {
                "total_discount": 1500.00,
                "total_vat_adjustment": 100.00,
                "by_type": {
                    "Senior Citizen": 750.00,
                    "PWD": 500.00,
                    ...
                }
            },
            "success": True
        }
    """
    try:
        df = pd.read_excel(io.BytesIO(file_content), header=None)
        metadata = _extract_metadata(df)

        # Find header row (row 9 in standard format)
        # Columns: Pos Date, Terminal Id, Location, Bill No, Discount Amount,
        # Vat Adjustment, VAT, Service Charge Amount, Sub Total, Other Charges,
        # Final Amount, Discount Name, Discount Type, Reference Number, Name,
        # Requested By, Time, Date

        # Read data starting from row 10
        data_df = pd.read_excel(io.BytesIO(file_content), header=9)
        data_df.columns = data_df.columns.str.strip()

        discounts = []
        discount_by_type = {}
        total_discount = 0.0
        total_vat_adjustment = 0.0

        for _, row in data_df.iterrows():
            # Skip empty rows
            if pd.isna(row.get("Bill No")):
                continue

            discount = {
                "pos_date": _parse_date(row.get("Pos Date")),
                "terminal_id": str(row.get("Terminal Id", "")) if pd.notna(row.get("Terminal Id")) else None,
                "location": str(row.get("Location", "")) if pd.notna(row.get("Location")) else None,
                "bill_no": _safe_int(row.get("Bill No")),
                "discount_amount": _safe_float(row.get("Discount Amount")),
                "vat_adjustment": _safe_float(row.get("Vat Adjustment")),
                "vat": _safe_float(row.get("VAT")),
                "subtotal": _safe_float(row.get("Sub Total")),
                "final_amount": _safe_float(row.get("Final Amount")),
                "discount_name": str(row.get("Discount Name", "")) if pd.notna(row.get("Discount Name")) else None,
                "discount_type": str(row.get("Discount Type", "")) if pd.notna(row.get("Discount Type")) else None,
                "reference_number": str(row.get("Reference Number", "")) if pd.notna(row.get("Reference Number")) else None,
                "customer_name": str(row.get("Name", "")) if pd.notna(row.get("Name")) else None,
            }

            discounts.append(discount)

            # Accumulate totals
            total_discount += discount["discount_amount"]
            total_vat_adjustment += discount["vat_adjustment"]

            discount_name = discount["discount_name"] or "Other"
            if discount_name not in discount_by_type:
                discount_by_type[discount_name] = 0.0
            discount_by_type[discount_name] += discount["discount_amount"]

        return {
            "metadata": metadata,
            "discounts": discounts,
            "totals": {
                "total_discount": total_discount,
                "total_vat_adjustment": total_vat_adjustment,
                "by_type": discount_by_type,
                "discount_count": len(discounts)
            },
            "success": True
        }

    except Exception as e:
        return {"success": False, "error": str(e)}


# ==============================================================================
# DAILY SALES REVENUE PARSER
# ==============================================================================

def parse_daily_sales_revenue(file_content: bytes) -> Dict[str, Any]:
    """
    Parse MOSAIC Daily Sales Revenue - Summary export.

    Contains per-transaction revenue with payment breakdown:
    - Net/Gross sales per transaction
    - Payment type per transaction
    - Order type and service channel

    Args:
        file_content: Excel file bytes

    Returns:
        Dictionary with extracted data:
        {
            "metadata": {...},
            "transactions": [...],
            "totals": {
                "gross_sales": 12345.00,
                "net_sales": 11000.00,
                "by_payment_type": {...},
                "by_order_type": {...}
            },
            "success": True
        }
    """
    try:
        df = pd.read_excel(io.BytesIO(file_content), header=None)
        metadata = _extract_metadata(df)

        # Read data starting from row 10 (header is row 9)
        # Columns: Location, Date, OR No, Bill No, Bill Time, Settle Date,
        # Settle Time, Manual SI No., Terminal Id, Cashier, Discount Amount,
        # Vat Adjustment, Tax Amount, VAT, Service Charge Amount, Net Sales,
        # Gross Sales, Gc Excess, Order Type, Service Channel, Payment Type,
        # More Details, Short Order Id, Customer Tin, Customer Name, Customer Address,
        # Customer Business Style

        data_df = pd.read_excel(io.BytesIO(file_content), header=9)
        data_df.columns = data_df.columns.str.strip()

        transactions = []
        gross_total = 0.0
        net_total = 0.0
        payment_totals = {}
        order_type_totals = {}

        for _, row in data_df.iterrows():
            # Skip empty rows and summary rows
            if pd.isna(row.get("Bill No")):
                continue

            tx = {
                "location": str(row.get("Location", "")) if pd.notna(row.get("Location")) else None,
                "date": _parse_date(row.get("Date")),
                "or_no": _safe_int(row.get("OR No")),
                "bill_no": _safe_int(row.get("Bill No")),
                "bill_time": str(row.get("Bill Time", "")) if pd.notna(row.get("Bill Time")) else None,
                "terminal_id": str(row.get("Terminal Id", "")) if pd.notna(row.get("Terminal Id")) else None,
                "cashier": str(row.get("Cashier", "")) if pd.notna(row.get("Cashier")) else None,
                "discount_amount": _safe_float(row.get("Discount Amount")),
                "vat_adjustment": _safe_float(row.get("Vat Adjustment")),
                "tax_amount": _safe_float(row.get("Tax Amount")),
                "vat": _safe_float(row.get("VAT")),
                "net_sales": _safe_float(row.get("Net Sales")),
                "gross_sales": _safe_float(row.get("Gross Sales")),
                "gc_excess": _safe_float(row.get("Gc Excess")),
                "order_type": str(row.get("Order Type", "")) if pd.notna(row.get("Order Type")) else None,
                "service_channel": str(row.get("Service Channel", "")) if pd.notna(row.get("Service Channel")) else None,
                "payment_type": str(row.get("Payment Type", "")) if pd.notna(row.get("Payment Type")) else None,
            }

            transactions.append(tx)

            # Accumulate totals
            gross_total += tx["gross_sales"]
            net_total += tx["net_sales"]

            # By payment type
            payment_type = tx["payment_type"] or "Unknown"
            if payment_type not in payment_totals:
                payment_totals[payment_type] = 0.0
            payment_totals[payment_type] += tx["gross_sales"]

            # By order type
            order_type = tx["order_type"] or "Unknown"
            if order_type not in order_type_totals:
                order_type_totals[order_type] = 0.0
            order_type_totals[order_type] += tx["gross_sales"]

        return {
            "metadata": metadata,
            "transactions": transactions,
            "totals": {
                "gross_sales": gross_total,
                "net_sales": net_total,
                "transaction_count": len(transactions),
                "by_payment_type": payment_totals,
                "by_order_type": order_type_totals
            },
            "success": True
        }

    except Exception as e:
        return {"success": False, "error": str(e)}


# ==============================================================================
# PRODUCT MIX PARSER (For BOM Deduction)
# ==============================================================================

def parse_product_mix(file_content: bytes) -> Dict[str, Any]:
    """
    Parse MOSAIC Product Mix export.

    Contains SKU-level sales data for BOM deduction:
    - Product/item codes
    - Quantities sold
    - Per-item pricing
    - Category breakdown

    Args:
        file_content: Excel file bytes

    Returns:
        Dictionary with extracted data:
        {
            "metadata": {...},
            "items": [...],
            "totals": {
                "total_qty": 357,
                "gross_sales": 65473.93,
                "net_sales": 55587.54,
                "by_category": {...}
            },
            "success": True
        }
    """
    try:
        df = pd.read_excel(io.BytesIO(file_content), header=None)
        metadata = _extract_metadata(df)

        # Product Mix has header at row 11
        # Columns: Location Name, Product Group, SKU/Item Code, Item Name,
        # Open Item, Forced Modifier Name, Unforced Modifier Name,
        # Per Price (item price w/o VAT), Total Forced Modifier Price with VAT,
        # Item Qty, Discount Qty, Complimentary/Non-Revenue Qty, Gross Sales,
        # Discount Amount, VAT Adjustment, VAT, Service Charge, Net Sales

        data_df = pd.read_excel(io.BytesIO(file_content), header=11)
        data_df.columns = data_df.columns.str.strip()

        items = []
        category_totals = {}
        total_qty = 0
        gross_total = 0.0
        net_total = 0.0

        for _, row in data_df.iterrows():
            # Skip empty rows and Grand Totals row
            location = row.get("Location Name")
            if pd.isna(location) or str(location).strip() in ["Grand Totals:", ""]:
                continue

            item = {
                "location": str(location) if pd.notna(location) else None,
                "product_group": str(row.get("Product Group", "")) if pd.notna(row.get("Product Group")) else None,
                "sku_code": str(row.get("SKU/Item Code", "")) if pd.notna(row.get("SKU/Item Code")) else None,
                "item_name": str(row.get("Item Name", "")) if pd.notna(row.get("Item Name")) else None,
                "is_open_item": str(row.get("Open Item", "No")).upper() == "YES",
                "unit_price": _safe_float(row.get("Per Price (item price w/o VAT)")),
                "qty_sold": _safe_int(row.get("Item Qty")),
                "qty_discount": _safe_int(row.get("Discount Qty")),
                "qty_complimentary": _safe_int(row.get("Complimentary/Non-Revenue Qty")),
                "gross_sales": _safe_float(row.get("Gross Sales")),
                "discount_amount": _safe_float(row.get("Discount Amount")),
                "vat_adjustment": _safe_float(row.get("VAT Adjustment")),
                "vat": _safe_float(row.get("VAT")),
                "net_sales": _safe_float(row.get("Net Sales")),
            }

            items.append(item)

            # Accumulate totals
            total_qty += item["qty_sold"]
            gross_total += item["gross_sales"]
            net_total += item["net_sales"]

            # By category
            category = item["product_group"] or "Uncategorized"
            if category not in category_totals:
                category_totals[category] = {"qty": 0, "gross_sales": 0.0, "net_sales": 0.0}
            category_totals[category]["qty"] += item["qty_sold"]
            category_totals[category]["gross_sales"] += item["gross_sales"]
            category_totals[category]["net_sales"] += item["net_sales"]

        return {
            "metadata": metadata,
            "items": items,
            "totals": {
                "total_qty": total_qty,
                "gross_sales": gross_total,
                "net_sales": net_total,
                "item_count": len(items),
                "by_category": category_totals
            },
            "success": True
        }

    except Exception as e:
        return {"success": False, "error": str(e)}


# ==============================================================================
# UNIFIED EXTRACTION FUNCTION
# ==============================================================================

def extract_all_pos_data(
    sales_summary_content: bytes = None,
    transaction_report_content: bytes = None,
    discount_report_content: bytes = None,
    daily_sales_revenue_content: bytes = None,
    product_mix_content: bytes = None
) -> Dict[str, Any]:
    """
    Extract data from all 5 POS file types.

    Args:
        sales_summary_content: Sales Summary Excel bytes
        transaction_report_content: Transaction Report Excel bytes
        discount_report_content: Discount Report Excel bytes
        daily_sales_revenue_content: Daily Sales Revenue Excel bytes
        product_mix_content: Product Mix Excel bytes

    Returns:
        Unified dictionary with all extracted data:
        {
            "sales_summary": {...},
            "transaction_report": {...},
            "discount_report": {...},
            "daily_sales_revenue": {...},
            "product_mix": {...},
            "consolidated": {
                "date": "2026-01-30",
                "store": "...",
                "gross_sales": 65473.93,
                "net_sales": 55587.54,
                "vat": 5575.48,
                "beginning_si": 45788,
                "ending_si": 46000,
                "transaction_count": 212,
                "eod_counter": 212,
                "discount_pwd": 500.00,
                "discount_senior": 750.00,
                "discount_other": 100.00,
                "total_discount": 1350.00,
                "by_payment_type": {...},
                "by_category": {...}
            },
            "success": True
        }
    """
    result = {
        "sales_summary": None,
        "transaction_report": None,
        "discount_report": None,
        "daily_sales_revenue": None,
        "product_mix": None,
        "consolidated": {},
        "success": True,
        "errors": []
    }

    # Parse each file if provided
    if sales_summary_content:
        result["sales_summary"] = parse_sales_summary(sales_summary_content)
        if not result["sales_summary"]["success"]:
            result["errors"].append(f"Sales Summary: {result['sales_summary'].get('error')}")

    if transaction_report_content:
        result["transaction_report"] = parse_transaction_report(transaction_report_content)
        if not result["transaction_report"]["success"]:
            result["errors"].append(f"Transaction Report: {result['transaction_report'].get('error')}")

    if discount_report_content:
        result["discount_report"] = parse_discount_report(discount_report_content)
        if not result["discount_report"]["success"]:
            result["errors"].append(f"Discount Report: {result['discount_report'].get('error')}")

    if daily_sales_revenue_content:
        result["daily_sales_revenue"] = parse_daily_sales_revenue(daily_sales_revenue_content)
        if not result["daily_sales_revenue"]["success"]:
            result["errors"].append(f"Daily Sales Revenue: {result['daily_sales_revenue'].get('error')}")

    if product_mix_content:
        result["product_mix"] = parse_product_mix(product_mix_content)
        if not result["product_mix"]["success"]:
            result["errors"].append(f"Product Mix: {result['product_mix'].get('error')}")

    # Build consolidated summary (primarily from Sales Summary)
    consolidated = {}

    if result["sales_summary"] and result["sales_summary"]["success"]:
        ss = result["sales_summary"]["summary"]
        consolidated.update({
            "date": ss.get("date"),
            "gross_sales": ss.get("gross_sales"),
            "net_sales": ss.get("net_sales"),
            "vat": ss.get("vat"),
            "vatable_sales": ss.get("vatable_sales"),
            "vat_exempt_sales": ss.get("vat_exempt_sales"),
            "zero_rated_sales": ss.get("zero_rated_sales"),
            "beginning_si": ss.get("beginning_si"),
            "ending_si": ss.get("ending_si"),
            "transaction_count": ss.get("transaction_count"),
            "eod_counter": ss.get("eod_counter"),
            "discount_pwd": ss.get("discount_pwd"),
            "discount_senior": ss.get("discount_senior"),
            "discount_other": ss.get("discount_other"),
            "vat_adjustment": ss.get("vat_adjustment"),
            "delivery_fee": ss.get("delivery_fee"),
            "gc_excess": ss.get("gc_excess"),
            "returns": ss.get("returns"),
            "void_count": ss.get("void_count"),
        })

        if result["sales_summary"].get("metadata"):
            consolidated["store"] = result["sales_summary"]["metadata"].get("location")
            consolidated["tin"] = result["sales_summary"]["metadata"].get("tin")

    # Add payment type breakdown from Transaction Report
    if result["transaction_report"] and result["transaction_report"]["success"]:
        consolidated["by_payment_type"] = result["transaction_report"]["totals"].get("by_payment_type", {})

    # Add category breakdown from Product Mix
    if result["product_mix"] and result["product_mix"]["success"]:
        consolidated["by_category"] = result["product_mix"]["totals"].get("by_category", {})
        consolidated["total_items_sold"] = result["product_mix"]["totals"].get("total_qty", 0)

    # Add discount breakdown from Discount Report
    if result["discount_report"] and result["discount_report"]["success"]:
        consolidated["discount_breakdown"] = result["discount_report"]["totals"].get("by_type", {})
        consolidated["discount_count"] = result["discount_report"]["totals"].get("discount_count", 0)

    # Calculate total discounts
    consolidated["total_discount"] = (
        consolidated.get("discount_pwd", 0) +
        consolidated.get("discount_senior", 0) +
        consolidated.get("discount_other", 0)
    )

    result["consolidated"] = consolidated

    if result["errors"]:
        result["success"] = False

    return result
