-- ============================================================================
-- Migration: Discount identity same-day alerts
-- Date: 2026-03-07
-- Why: Flag repeated Senior Citizen / PWD names and reference numbers directly
--      in Supabase so audit can review same-day reuse within one store or
--      across multiple stores without relying on external scripts.
-- Notes:
--   - Counts distinct orders, not item rows.
--   - Collapses duplicate item lines within the same receipt to one identity
--     row per order/category/name/reference combination.
--   - Reuses public.discount_abuse_alerts and its unique key.
--   - Scheduling is intentionally left for a separate approval step.
-- ============================================================================

alter table public.pos_order_items
  add column if not exists discount_name_normalized text,
  add column if not exists discount_customer_full_name text,
  add column if not exists discount_customer_full_name_normalized text,
  add column if not exists discount_reference_number_normalized text,
  add column if not exists discount_bir_category text,
  add column if not exists discount_payload jsonb;

create table if not exists public.discount_abuse_alerts (
  id bigint generated by default as identity primary key,
  business_date date not null,
  scope text not null,
  scope_key integer not null,
  location_id integer,
  store_name text,
  discount_name text,
  discount_bir_category text not null,
  identity_type text not null,
  identity_key text not null,
  customer_name text,
  reference_number text,
  order_count integer not null default 0,
  store_count integer not null default 0,
  detection_type text not null,
  severity text not null,
  details jsonb not null default '{}'::jsonb,
  resolved boolean not null default false,
  resolved_at timestamptz,
  notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_discount_abuse_alerts_date_resolved
  on public.discount_abuse_alerts (business_date, resolved, severity);

create unique index if not exists uq_discount_abuse_alert_identity
  on public.discount_abuse_alerts (
    business_date,
    scope,
    scope_key,
    discount_bir_category,
    identity_type,
    identity_key,
    detection_type
  );

alter table public.discount_abuse_alerts
  drop constraint if exists discount_abuse_alerts_detection_type_check;

alter table public.discount_abuse_alerts
  add constraint discount_abuse_alerts_detection_type_check
  check (
    detection_type = any (
      array[
        'repeat_reference'::text,
        'repeat_name'::text,
        'cross_store_identity'::text,
        'same_name_same_day_same_store'::text,
        'same_name_same_day_multi_store'::text,
        'same_name_diff_reference_same_day_same_store'::text,
        'same_name_diff_reference_same_day_multi_store'::text,
        'same_reference_same_day_same_store'::text,
        'same_reference_same_day_multi_store'::text,
        'same_reference_diff_name_same_day_same_store'::text,
        'same_reference_diff_name_same_day_multi_store'::text
      ]
    )
  );

create table if not exists public.discount_identity_30d_snapshots (
  id bigint generated by default as identity primary key,
  as_of_date date not null,
  window_start date not null,
  window_end date not null,
  scope text not null,
  scope_key integer not null,
  location_id integer not null,
  store_name text,
  discount_name text,
  discount_bir_category text not null,
  identity_type text not null,
  identity_key text not null,
  customer_name text,
  reference_number text,
  order_count integer not null default 0,
  active_day_count integer not null default 0,
  distinct_counterparty_count integer not null default 0,
  detection_type text not null,
  severity text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_discount_identity_30d_snapshots_date_store
  on public.discount_identity_30d_snapshots (as_of_date, location_id, severity);

create unique index if not exists uq_discount_identity_30d_snapshot
  on public.discount_identity_30d_snapshots (
    as_of_date,
    scope,
    scope_key,
    discount_bir_category,
    identity_type,
    identity_key,
    detection_type
  );

create or replace view public.v_discount_identity_order_usage as
with normalized_source as (
  select
    po.business_date,
    po.location_id,
    coalesce(s.store_name, 'Location ' || po.location_id::text) as store_name,
    po.id as order_id,
    po.bill_number,
    po.receipt_number,
    po.billed_at,
    po.paid_at,
    case
      when upper(coalesce(poi.discount_bir_category, '')) in ('SC', 'PWD')
        then upper(poi.discount_bir_category)
      when upper(coalesce(poi.discount_name_normalized, poi.discount_name, '')) like '%SENIOR%'
        then 'SC'
      when upper(coalesce(poi.discount_name_normalized, poi.discount_name, '')) like '%PWD%'
        then 'PWD'
      else null
    end as discount_bir_category,
    upper(
      nullif(
        trim(
          regexp_replace(
            coalesce(
              nullif(poi.discount_customer_full_name_normalized, ''),
              nullif(poi.discount_customer_full_name, ''),
              nullif(trim(concat_ws(' ', poi.discount_customer_first_name, poi.discount_customer_last_name)), '')
            ),
            '\s+',
            ' ',
            'g'
          )
        ),
        ''
      )
    ) as full_name_normalized,
    upper(
      nullif(
        regexp_replace(
          coalesce(
            nullif(poi.discount_reference_number_normalized, ''),
            nullif(trim(poi.discount_reference_number), ''),
            ''
          ),
          '[^A-Za-z0-9]+',
          '',
          'g'
        ),
        ''
      )
    ) as reference_number_normalized,
    coalesce(
      nullif(trim(poi.discount_customer_full_name), ''),
      nullif(trim(concat_ws(' ', poi.discount_customer_first_name, poi.discount_customer_last_name)), '')
    ) as customer_name_display,
    coalesce(
      nullif(trim(poi.discount_reference_number), ''),
      nullif(trim(poi.discount_reference_number_normalized), '')
    ) as reference_number_display,
    upper(
      nullif(
        trim(
          regexp_replace(
            coalesce(poi.discount_name_normalized, poi.discount_name, ''),
            '\s+',
            ' ',
            'g'
          )
        ),
        ''
      )
    ) as discount_name_normalized,
    coalesce(poi.discount_amount, 0)::numeric as discount_amount
  from public.pos_order_items poi
  join public.pos_orders po
    on po.id = poi.order_id
  left join public.stores s
    on s.location_id = po.location_id
  where po.payment_status = 'PAID'
),
identity_usage as (
  select
    business_date,
    location_id,
    store_name,
    order_id,
    bill_number,
    receipt_number,
    billed_at,
    paid_at,
    discount_bir_category,
    full_name_normalized,
    reference_number_normalized,
    max(customer_name_display) as customer_name_display,
    max(reference_number_display) as reference_number_display,
    max(discount_name_normalized) as discount_name_normalized,
    round(sum(discount_amount)::numeric, 2) as discount_amount_total
  from normalized_source
  where discount_bir_category is not null
    and (full_name_normalized is not null or reference_number_normalized is not null)
  group by
    business_date,
    location_id,
    store_name,
    order_id,
    bill_number,
    receipt_number,
    billed_at,
    paid_at,
    discount_bir_category,
    full_name_normalized,
    reference_number_normalized
)
select
  business_date,
  location_id,
  store_name,
  order_id,
  bill_number,
  receipt_number,
  billed_at,
  paid_at,
  discount_bir_category,
  coalesce(
    discount_name_normalized,
    case discount_bir_category
      when 'SC' then 'SENIOR CITIZEN DISCOUNT'
      when 'PWD' then 'PWD'
      else discount_bir_category
    end
  ) as discount_name_normalized,
  full_name_normalized,
  reference_number_normalized,
  customer_name_display,
  reference_number_display,
  discount_amount_total
from identity_usage;

create or replace view public.v_discount_identity_rolling_30d_usage as
with base as (
  select
    (current_date - interval '29 days')::date as window_start,
    current_date::date as window_end,
    business_date,
    location_id,
    store_name,
    order_id,
    bill_number,
    receipt_number,
    billed_at,
    paid_at,
    discount_bir_category,
    discount_name_normalized,
    full_name_normalized,
    reference_number_normalized,
    customer_name_display,
    reference_number_display,
    discount_amount_total
  from public.v_discount_identity_order_usage
  where business_date between (current_date - interval '29 days')::date and current_date::date
),
name_usage as (
  select
    window_start,
    window_end,
    location_id,
    max(store_name) as store_name,
    discount_bir_category,
    max(discount_name_normalized) as discount_name,
    full_name_normalized as identity_key,
    array_agg(distinct customer_name_display order by customer_name_display)
      filter (where customer_name_display is not null) as customer_names,
    array_agg(distinct reference_number_display order by reference_number_display)
      filter (where reference_number_display is not null) as reference_numbers,
    array_agg(distinct order_id order by order_id) as order_ids,
    array_agg(distinct bill_number::text order by bill_number::text)
      filter (where bill_number is not null) as bill_numbers,
    array_agg(distinct receipt_number::text order by receipt_number::text)
      filter (where receipt_number is not null) as receipt_numbers,
    array_agg(distinct business_date order by business_date) as business_dates,
    count(distinct order_id)::integer as order_count,
    count(distinct business_date)::integer as active_day_count,
    count(distinct reference_number_normalized)::integer as distinct_counterparty_count,
    min(billed_at) as first_billed_at,
    max(billed_at) as last_billed_at,
    min(paid_at) as first_paid_at,
    max(paid_at) as last_paid_at,
    round(sum(discount_amount_total)::numeric, 2) as discount_amount_total
  from base
  where full_name_normalized is not null
  group by window_start, window_end, location_id, discount_bir_category, full_name_normalized
),
reference_usage as (
  select
    window_start,
    window_end,
    location_id,
    max(store_name) as store_name,
    discount_bir_category,
    max(discount_name_normalized) as discount_name,
    reference_number_normalized as identity_key,
    array_agg(distinct customer_name_display order by customer_name_display)
      filter (where customer_name_display is not null) as customer_names,
    array_agg(distinct reference_number_display order by reference_number_display)
      filter (where reference_number_display is not null) as reference_numbers,
    array_agg(distinct order_id order by order_id) as order_ids,
    array_agg(distinct bill_number::text order by bill_number::text)
      filter (where bill_number is not null) as bill_numbers,
    array_agg(distinct receipt_number::text order by receipt_number::text)
      filter (where receipt_number is not null) as receipt_numbers,
    array_agg(distinct business_date order by business_date) as business_dates,
    count(distinct order_id)::integer as order_count,
    count(distinct business_date)::integer as active_day_count,
    count(distinct full_name_normalized)::integer as distinct_counterparty_count,
    min(billed_at) as first_billed_at,
    max(billed_at) as last_billed_at,
    min(paid_at) as first_paid_at,
    max(paid_at) as last_paid_at,
    round(sum(discount_amount_total)::numeric, 2) as discount_amount_total
  from base
  where reference_number_normalized is not null
  group by window_start, window_end, location_id, discount_bir_category, reference_number_normalized
)
select
  window_start,
  window_end,
  location_id,
  store_name,
  discount_bir_category,
  discount_name,
  'full_name'::text as identity_type,
  identity_key,
  customer_names[1] as customer_name,
  case when distinct_counterparty_count = 1 then reference_numbers[1] else null end as reference_number,
  order_count,
  active_day_count,
  distinct_counterparty_count,
  discount_amount_total,
  jsonb_build_object(
    'customer_names', to_jsonb(coalesce(customer_names, array[]::text[])),
    'reference_numbers', to_jsonb(coalesce(reference_numbers, array[]::text[])),
    'order_ids', to_jsonb(order_ids),
    'bill_numbers', to_jsonb(coalesce(bill_numbers, array[]::text[])),
    'receipt_numbers', to_jsonb(coalesce(receipt_numbers, array[]::text[])),
    'business_dates', to_jsonb(business_dates),
    'first_billed_at', first_billed_at,
    'last_billed_at', last_billed_at,
    'first_paid_at', first_paid_at,
    'last_paid_at', last_paid_at
  ) as details
from name_usage

union all

select
  window_start,
  window_end,
  location_id,
  store_name,
  discount_bir_category,
  discount_name,
  'reference_number'::text as identity_type,
  identity_key,
  case when distinct_counterparty_count = 1 then customer_names[1] else null end as customer_name,
  reference_numbers[1] as reference_number,
  order_count,
  active_day_count,
  distinct_counterparty_count,
  discount_amount_total,
  jsonb_build_object(
    'customer_names', to_jsonb(coalesce(customer_names, array[]::text[])),
    'reference_numbers', to_jsonb(coalesce(reference_numbers, array[]::text[])),
    'order_ids', to_jsonb(order_ids),
    'bill_numbers', to_jsonb(coalesce(bill_numbers, array[]::text[])),
    'receipt_numbers', to_jsonb(coalesce(receipt_numbers, array[]::text[])),
    'business_dates', to_jsonb(business_dates),
    'first_billed_at', first_billed_at,
    'last_billed_at', last_billed_at,
    'first_paid_at', first_paid_at,
    'last_paid_at', last_paid_at
  ) as details
from reference_usage;

create or replace function public.refresh_discount_identity_alerts(
  p_business_date date default null,
  p_categories text[] default array['SC']
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_categories text[];
  v_detection_types constant text[] := array[
    'same_name_same_day_same_store',
    'same_name_same_day_multi_store',
    'same_name_diff_reference_same_day_same_store',
    'same_name_diff_reference_same_day_multi_store',
    'same_reference_same_day_same_store',
    'same_reference_same_day_multi_store',
    'same_reference_diff_name_same_day_same_store',
    'same_reference_diff_name_same_day_multi_store'
  ];
  v_alert_count integer := 0;
begin
  select coalesce(array_agg(category), array[]::text[])
    into v_categories
  from (
    select distinct upper(trim(x)) as category
    from unnest(coalesce(p_categories, array['SC'])) as t(x)
    where nullif(trim(x), '') is not null
  ) normalized_categories;

  if cardinality(v_categories) = 0 then
    raise exception 'refresh_discount_identity_alerts(): p_categories must contain at least one non-empty value';
  end if;

  create temp table tmp_discount_identity_alerts on commit drop as
  with base as (
    select
      business_date,
      location_id,
      store_name,
      order_id,
      bill_number,
      receipt_number,
      billed_at,
      paid_at,
      discount_bir_category,
      discount_name_normalized,
      full_name_normalized,
      reference_number_normalized,
      coalesce(customer_name_display, full_name_normalized) as customer_name_display,
      coalesce(reference_number_display, reference_number_normalized) as reference_number_display,
      discount_amount_total
    from public.v_discount_identity_order_usage
    where discount_bir_category = any (v_categories)
      and (p_business_date is null or business_date = p_business_date)
  ),
  name_store_ranked as (
    select
      b.*,
      lead(billed_at) over (
        partition by business_date, location_id, discount_bir_category, full_name_normalized
        order by billed_at nulls last, order_id
      ) as next_billed_at
    from base b
    where full_name_normalized is not null
  ),
  name_store_groups as (
    select
      business_date,
      location_id,
      max(store_name) as store_name,
      discount_bir_category,
      full_name_normalized as identity_key,
      max(discount_name_normalized) as discount_name,
      array_agg(distinct customer_name_display order by customer_name_display)
        filter (where customer_name_display is not null) as customer_names,
      array_agg(distinct reference_number_display order by reference_number_display)
        filter (where reference_number_display is not null) as reference_numbers,
      array_agg(distinct reference_number_normalized order by reference_number_normalized)
        filter (where reference_number_normalized is not null) as reference_keys,
      array_agg(distinct order_id order by order_id) as order_ids,
      array_agg(distinct bill_number::text order by bill_number::text)
        filter (where bill_number is not null) as bill_numbers,
      array_agg(distinct receipt_number::text order by receipt_number::text)
        filter (where receipt_number is not null) as receipt_numbers,
      count(distinct order_id)::integer as order_count,
      count(distinct reference_number_normalized)::integer as distinct_reference_count,
      min(billed_at) as first_billed_at,
      max(billed_at) as last_billed_at,
      min(paid_at) as first_paid_at,
      max(paid_at) as last_paid_at,
      min(round((extract(epoch from (next_billed_at - billed_at)) / 60.0)::numeric, 1))
        filter (where billed_at is not null and next_billed_at is not null) as min_gap_minutes,
      round(sum(discount_amount_total)::numeric, 2) as discount_amount_total
    from name_store_ranked
    group by business_date, location_id, discount_bir_category, full_name_normalized
    having count(distinct order_id) >= 2
  ),
  name_multi_store_ranked as (
    select
      b.*,
      lead(billed_at) over (
        partition by business_date, discount_bir_category, full_name_normalized
        order by billed_at nulls last, order_id
      ) as next_billed_at
    from base b
    where full_name_normalized is not null
  ),
  name_multi_store_groups as (
    select
      business_date,
      discount_bir_category,
      full_name_normalized as identity_key,
      max(discount_name_normalized) as discount_name,
      array_agg(distinct location_id order by location_id) as location_ids,
      array_agg(distinct store_name order by store_name)
        filter (where store_name is not null) as store_names,
      array_agg(distinct customer_name_display order by customer_name_display)
        filter (where customer_name_display is not null) as customer_names,
      array_agg(distinct reference_number_display order by reference_number_display)
        filter (where reference_number_display is not null) as reference_numbers,
      array_agg(distinct reference_number_normalized order by reference_number_normalized)
        filter (where reference_number_normalized is not null) as reference_keys,
      array_agg(distinct order_id order by order_id) as order_ids,
      array_agg(distinct bill_number::text order by bill_number::text)
        filter (where bill_number is not null) as bill_numbers,
      count(distinct order_id)::integer as order_count,
      count(distinct location_id)::integer as store_count,
      count(distinct reference_number_normalized)::integer as distinct_reference_count,
      min(billed_at) as first_billed_at,
      max(billed_at) as last_billed_at,
      min(paid_at) as first_paid_at,
      max(paid_at) as last_paid_at,
      min(round((extract(epoch from (next_billed_at - billed_at)) / 60.0)::numeric, 1))
        filter (where billed_at is not null and next_billed_at is not null) as min_gap_minutes,
      round(sum(discount_amount_total)::numeric, 2) as discount_amount_total
    from name_multi_store_ranked
    group by business_date, discount_bir_category, full_name_normalized
    having count(distinct location_id) >= 2
       and count(distinct order_id) >= 2
  ),
  ref_store_ranked as (
    select
      b.*,
      lead(billed_at) over (
        partition by business_date, location_id, discount_bir_category, reference_number_normalized
        order by billed_at nulls last, order_id
      ) as next_billed_at
    from base b
    where reference_number_normalized is not null
  ),
  ref_store_groups as (
    select
      business_date,
      location_id,
      max(store_name) as store_name,
      discount_bir_category,
      reference_number_normalized as identity_key,
      max(discount_name_normalized) as discount_name,
      array_agg(distinct customer_name_display order by customer_name_display)
        filter (where customer_name_display is not null) as customer_names,
      array_agg(distinct reference_number_display order by reference_number_display)
        filter (where reference_number_display is not null) as reference_numbers,
      array_agg(distinct full_name_normalized order by full_name_normalized)
        filter (where full_name_normalized is not null) as name_keys,
      array_agg(distinct order_id order by order_id) as order_ids,
      array_agg(distinct bill_number::text order by bill_number::text)
        filter (where bill_number is not null) as bill_numbers,
      array_agg(distinct receipt_number::text order by receipt_number::text)
        filter (where receipt_number is not null) as receipt_numbers,
      count(distinct order_id)::integer as order_count,
      count(distinct full_name_normalized)::integer as distinct_name_count,
      min(billed_at) as first_billed_at,
      max(billed_at) as last_billed_at,
      min(paid_at) as first_paid_at,
      max(paid_at) as last_paid_at,
      min(round((extract(epoch from (next_billed_at - billed_at)) / 60.0)::numeric, 1))
        filter (where billed_at is not null and next_billed_at is not null) as min_gap_minutes,
      round(sum(discount_amount_total)::numeric, 2) as discount_amount_total
    from ref_store_ranked
    group by business_date, location_id, discount_bir_category, reference_number_normalized
    having count(distinct order_id) >= 2
  ),
  ref_multi_store_ranked as (
    select
      b.*,
      lead(billed_at) over (
        partition by business_date, discount_bir_category, reference_number_normalized
        order by billed_at nulls last, order_id
      ) as next_billed_at
    from base b
    where reference_number_normalized is not null
  ),
  ref_multi_store_groups as (
    select
      business_date,
      discount_bir_category,
      reference_number_normalized as identity_key,
      max(discount_name_normalized) as discount_name,
      array_agg(distinct location_id order by location_id) as location_ids,
      array_agg(distinct store_name order by store_name)
        filter (where store_name is not null) as store_names,
      array_agg(distinct customer_name_display order by customer_name_display)
        filter (where customer_name_display is not null) as customer_names,
      array_agg(distinct reference_number_display order by reference_number_display)
        filter (where reference_number_display is not null) as reference_numbers,
      array_agg(distinct full_name_normalized order by full_name_normalized)
        filter (where full_name_normalized is not null) as name_keys,
      array_agg(distinct order_id order by order_id) as order_ids,
      array_agg(distinct bill_number::text order by bill_number::text)
        filter (where bill_number is not null) as bill_numbers,
      count(distinct order_id)::integer as order_count,
      count(distinct location_id)::integer as store_count,
      count(distinct full_name_normalized)::integer as distinct_name_count,
      min(billed_at) as first_billed_at,
      max(billed_at) as last_billed_at,
      min(paid_at) as first_paid_at,
      max(paid_at) as last_paid_at,
      min(round((extract(epoch from (next_billed_at - billed_at)) / 60.0)::numeric, 1))
        filter (where billed_at is not null and next_billed_at is not null) as min_gap_minutes,
      round(sum(discount_amount_total)::numeric, 2) as discount_amount_total
    from ref_multi_store_ranked
    group by business_date, discount_bir_category, reference_number_normalized
    having count(distinct location_id) >= 2
       and count(distinct order_id) >= 2
  ),
  computed_alerts as (
    select
      business_date,
      'store'::text as scope,
      location_id as scope_key,
      location_id,
      store_name,
      discount_name,
      discount_bir_category,
      'full_name'::text as identity_type,
      identity_key,
      customer_names[1] as customer_name,
      case when distinct_reference_count = 1 then reference_numbers[1] else null end as reference_number,
      order_count,
      1::integer as store_count,
      'same_name_same_day_same_store'::text as detection_type,
      'medium'::text as severity,
      jsonb_build_object(
        'location_ids', to_jsonb(array[location_id]),
        'store_names', to_jsonb(array[store_name]),
        'order_ids', to_jsonb(order_ids),
        'bill_numbers', to_jsonb(coalesce(bill_numbers, array[]::text[])),
        'receipt_numbers', to_jsonb(coalesce(receipt_numbers, array[]::text[])),
        'customer_names', to_jsonb(coalesce(customer_names, array[]::text[])),
        'reference_numbers', to_jsonb(coalesce(reference_numbers, array[]::text[])),
        'distinct_reference_count', distinct_reference_count,
        'first_billed_at', first_billed_at,
        'last_billed_at', last_billed_at,
        'first_paid_at', first_paid_at,
        'last_paid_at', last_paid_at,
        'min_gap_minutes', min_gap_minutes,
        'rapid_within_4h', coalesce(min_gap_minutes <= 240, false),
        'discount_amount_total', discount_amount_total
      ) as details
    from name_store_groups

    union all

    select
      business_date,
      'chain'::text as scope,
      0 as scope_key,
      0 as location_id,
      array_to_string(store_names, ' | ') as store_name,
      discount_name,
      discount_bir_category,
      'full_name'::text as identity_type,
      identity_key,
      customer_names[1] as customer_name,
      case when distinct_reference_count = 1 then reference_numbers[1] else null end as reference_number,
      order_count,
      store_count,
      'same_name_same_day_multi_store'::text as detection_type,
      'medium'::text as severity,
      jsonb_build_object(
        'location_ids', to_jsonb(location_ids),
        'store_names', to_jsonb(coalesce(store_names, array[]::text[])),
        'order_ids', to_jsonb(order_ids),
        'bill_numbers', to_jsonb(coalesce(bill_numbers, array[]::text[])),
        'customer_names', to_jsonb(coalesce(customer_names, array[]::text[])),
        'reference_numbers', to_jsonb(coalesce(reference_numbers, array[]::text[])),
        'distinct_reference_count', distinct_reference_count,
        'first_billed_at', first_billed_at,
        'last_billed_at', last_billed_at,
        'first_paid_at', first_paid_at,
        'last_paid_at', last_paid_at,
        'min_gap_minutes', min_gap_minutes,
        'rapid_within_4h', coalesce(min_gap_minutes <= 240, false),
        'discount_amount_total', discount_amount_total
      ) as details
    from name_multi_store_groups

    union all

    select
      business_date,
      'store'::text as scope,
      location_id as scope_key,
      location_id,
      store_name,
      discount_name,
      discount_bir_category,
      'full_name'::text as identity_type,
      identity_key,
      customer_names[1] as customer_name,
      null::text as reference_number,
      order_count,
      1::integer as store_count,
      'same_name_diff_reference_same_day_same_store'::text as detection_type,
      'high'::text as severity,
      jsonb_build_object(
        'location_ids', to_jsonb(array[location_id]),
        'store_names', to_jsonb(array[store_name]),
        'order_ids', to_jsonb(order_ids),
        'bill_numbers', to_jsonb(coalesce(bill_numbers, array[]::text[])),
        'receipt_numbers', to_jsonb(coalesce(receipt_numbers, array[]::text[])),
        'customer_names', to_jsonb(coalesce(customer_names, array[]::text[])),
        'reference_numbers', to_jsonb(coalesce(reference_numbers, array[]::text[])),
        'distinct_reference_count', distinct_reference_count,
        'first_billed_at', first_billed_at,
        'last_billed_at', last_billed_at,
        'first_paid_at', first_paid_at,
        'last_paid_at', last_paid_at,
        'min_gap_minutes', min_gap_minutes,
        'rapid_within_4h', coalesce(min_gap_minutes <= 240, false),
        'discount_amount_total', discount_amount_total
      ) as details
    from name_store_groups
    where distinct_reference_count > 1

    union all

    select
      business_date,
      'chain'::text as scope,
      0 as scope_key,
      0 as location_id,
      array_to_string(store_names, ' | ') as store_name,
      discount_name,
      discount_bir_category,
      'full_name'::text as identity_type,
      identity_key,
      customer_names[1] as customer_name,
      null::text as reference_number,
      order_count,
      store_count,
      'same_name_diff_reference_same_day_multi_store'::text as detection_type,
      'high'::text as severity,
      jsonb_build_object(
        'location_ids', to_jsonb(location_ids),
        'store_names', to_jsonb(coalesce(store_names, array[]::text[])),
        'order_ids', to_jsonb(order_ids),
        'bill_numbers', to_jsonb(coalesce(bill_numbers, array[]::text[])),
        'customer_names', to_jsonb(coalesce(customer_names, array[]::text[])),
        'reference_numbers', to_jsonb(coalesce(reference_numbers, array[]::text[])),
        'distinct_reference_count', distinct_reference_count,
        'first_billed_at', first_billed_at,
        'last_billed_at', last_billed_at,
        'first_paid_at', first_paid_at,
        'last_paid_at', last_paid_at,
        'min_gap_minutes', min_gap_minutes,
        'rapid_within_4h', coalesce(min_gap_minutes <= 240, false),
        'discount_amount_total', discount_amount_total
      ) as details
    from name_multi_store_groups
    where distinct_reference_count > 1

    union all

    select
      business_date,
      'store'::text as scope,
      location_id as scope_key,
      location_id,
      store_name,
      discount_name,
      discount_bir_category,
      'reference_number'::text as identity_type,
      identity_key,
      case when distinct_name_count = 1 then customer_names[1] else null end as customer_name,
      reference_numbers[1] as reference_number,
      order_count,
      1::integer as store_count,
      'same_reference_same_day_same_store'::text as detection_type,
      'high'::text as severity,
      jsonb_build_object(
        'location_ids', to_jsonb(array[location_id]),
        'store_names', to_jsonb(array[store_name]),
        'order_ids', to_jsonb(order_ids),
        'bill_numbers', to_jsonb(coalesce(bill_numbers, array[]::text[])),
        'receipt_numbers', to_jsonb(coalesce(receipt_numbers, array[]::text[])),
        'customer_names', to_jsonb(coalesce(customer_names, array[]::text[])),
        'reference_numbers', to_jsonb(coalesce(reference_numbers, array[]::text[])),
        'distinct_name_count', distinct_name_count,
        'first_billed_at', first_billed_at,
        'last_billed_at', last_billed_at,
        'first_paid_at', first_paid_at,
        'last_paid_at', last_paid_at,
        'min_gap_minutes', min_gap_minutes,
        'rapid_within_4h', coalesce(min_gap_minutes <= 240, false),
        'discount_amount_total', discount_amount_total
      ) as details
    from ref_store_groups

    union all

    select
      business_date,
      'chain'::text as scope,
      0 as scope_key,
      0 as location_id,
      array_to_string(store_names, ' | ') as store_name,
      discount_name,
      discount_bir_category,
      'reference_number'::text as identity_type,
      identity_key,
      case when distinct_name_count = 1 then customer_names[1] else null end as customer_name,
      reference_numbers[1] as reference_number,
      order_count,
      store_count,
      'same_reference_same_day_multi_store'::text as detection_type,
      'critical'::text as severity,
      jsonb_build_object(
        'location_ids', to_jsonb(location_ids),
        'store_names', to_jsonb(coalesce(store_names, array[]::text[])),
        'order_ids', to_jsonb(order_ids),
        'bill_numbers', to_jsonb(coalesce(bill_numbers, array[]::text[])),
        'customer_names', to_jsonb(coalesce(customer_names, array[]::text[])),
        'reference_numbers', to_jsonb(coalesce(reference_numbers, array[]::text[])),
        'distinct_name_count', distinct_name_count,
        'first_billed_at', first_billed_at,
        'last_billed_at', last_billed_at,
        'first_paid_at', first_paid_at,
        'last_paid_at', last_paid_at,
        'min_gap_minutes', min_gap_minutes,
        'rapid_within_4h', coalesce(min_gap_minutes <= 240, false),
        'discount_amount_total', discount_amount_total
      ) as details
    from ref_multi_store_groups

    union all

    select
      business_date,
      'store'::text as scope,
      location_id as scope_key,
      location_id,
      store_name,
      discount_name,
      discount_bir_category,
      'reference_number'::text as identity_type,
      identity_key,
      null::text as customer_name,
      reference_numbers[1] as reference_number,
      order_count,
      1::integer as store_count,
      'same_reference_diff_name_same_day_same_store'::text as detection_type,
      'critical'::text as severity,
      jsonb_build_object(
        'location_ids', to_jsonb(array[location_id]),
        'store_names', to_jsonb(array[store_name]),
        'order_ids', to_jsonb(order_ids),
        'bill_numbers', to_jsonb(coalesce(bill_numbers, array[]::text[])),
        'receipt_numbers', to_jsonb(coalesce(receipt_numbers, array[]::text[])),
        'customer_names', to_jsonb(coalesce(customer_names, array[]::text[])),
        'reference_numbers', to_jsonb(coalesce(reference_numbers, array[]::text[])),
        'distinct_name_count', distinct_name_count,
        'first_billed_at', first_billed_at,
        'last_billed_at', last_billed_at,
        'first_paid_at', first_paid_at,
        'last_paid_at', last_paid_at,
        'min_gap_minutes', min_gap_minutes,
        'rapid_within_4h', coalesce(min_gap_minutes <= 240, false),
        'discount_amount_total', discount_amount_total
      ) as details
    from ref_store_groups
    where distinct_name_count > 1

    union all

    select
      business_date,
      'chain'::text as scope,
      0 as scope_key,
      0 as location_id,
      array_to_string(store_names, ' | ') as store_name,
      discount_name,
      discount_bir_category,
      'reference_number'::text as identity_type,
      identity_key,
      null::text as customer_name,
      reference_numbers[1] as reference_number,
      order_count,
      store_count,
      'same_reference_diff_name_same_day_multi_store'::text as detection_type,
      'critical'::text as severity,
      jsonb_build_object(
        'location_ids', to_jsonb(location_ids),
        'store_names', to_jsonb(coalesce(store_names, array[]::text[])),
        'order_ids', to_jsonb(order_ids),
        'bill_numbers', to_jsonb(coalesce(bill_numbers, array[]::text[])),
        'customer_names', to_jsonb(coalesce(customer_names, array[]::text[])),
        'reference_numbers', to_jsonb(coalesce(reference_numbers, array[]::text[])),
        'distinct_name_count', distinct_name_count,
        'first_billed_at', first_billed_at,
        'last_billed_at', last_billed_at,
        'first_paid_at', first_paid_at,
        'last_paid_at', last_paid_at,
        'min_gap_minutes', min_gap_minutes,
        'rapid_within_4h', coalesce(min_gap_minutes <= 240, false),
        'discount_amount_total', discount_amount_total
      ) as details
    from ref_multi_store_groups
    where distinct_name_count > 1
  )
  select *
  from computed_alerts;

  update public.discount_abuse_alerts existing
  set
    resolved = true,
    resolved_at = coalesce(existing.resolved_at, now()),
    updated_at = now()
  where existing.detection_type = any (v_detection_types)
    and existing.discount_bir_category = any (v_categories)
    and (p_business_date is null or existing.business_date = p_business_date)
    and not exists (
      select 1
      from tmp_discount_identity_alerts fresh
      where fresh.business_date = existing.business_date
        and fresh.scope = existing.scope
        and fresh.scope_key = existing.scope_key
        and fresh.discount_bir_category = existing.discount_bir_category
        and fresh.identity_type = existing.identity_type
        and fresh.identity_key = existing.identity_key
        and fresh.detection_type = existing.detection_type
    );

  insert into public.discount_abuse_alerts (
    business_date,
    scope,
    scope_key,
    location_id,
    store_name,
    discount_name,
    discount_bir_category,
    identity_type,
    identity_key,
    customer_name,
    reference_number,
    order_count,
    store_count,
    detection_type,
    severity,
    details,
    resolved,
    resolved_at,
    created_at,
    updated_at
  )
  select
    business_date,
    scope,
    scope_key,
    location_id,
    store_name,
    discount_name,
    discount_bir_category,
    identity_type,
    identity_key,
    customer_name,
    reference_number,
    order_count,
    store_count,
    detection_type,
    severity,
    details,
    false as resolved,
    null::timestamptz as resolved_at,
    now() as created_at,
    now() as updated_at
  from tmp_discount_identity_alerts
  on conflict (
    business_date,
    scope,
    scope_key,
    discount_bir_category,
    identity_type,
    identity_key,
    detection_type
  )
  do update
    set location_id = excluded.location_id,
        store_name = excluded.store_name,
        discount_name = excluded.discount_name,
        customer_name = excluded.customer_name,
        reference_number = excluded.reference_number,
        order_count = excluded.order_count,
        store_count = excluded.store_count,
        severity = excluded.severity,
        details = excluded.details,
        resolved = false,
        resolved_at = null,
        updated_at = now();

  select count(*)
    into v_alert_count
  from tmp_discount_identity_alerts;

  return v_alert_count;
end;
$$;

create or replace function public.refresh_discount_rolling_30d_identity_alerts(
  p_as_of_date date default current_date,
  p_categories text[] default array['SC', 'PWD'],
  p_name_order_threshold integer default 4,
  p_reference_order_threshold integer default 4
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_as_of_date date := coalesce(p_as_of_date, current_date);
  v_window_start date := (coalesce(p_as_of_date, current_date) - interval '29 days')::date;
  v_categories text[];
  v_detection_types constant text[] := array[
    'rolling_30d_name_threshold_same_store',
    'rolling_30d_name_diff_reference_threshold_same_store',
    'rolling_30d_reference_threshold_same_store',
    'rolling_30d_reference_diff_name_threshold_same_store'
  ];
  v_alert_count integer := 0;
begin
  select coalesce(array_agg(category), array[]::text[])
    into v_categories
  from (
    select distinct upper(trim(x)) as category
    from unnest(coalesce(p_categories, array['SC', 'PWD'])) as t(x)
    where nullif(trim(x), '') is not null
  ) normalized_categories;

  if cardinality(v_categories) = 0 then
    raise exception 'refresh_discount_rolling_30d_identity_alerts(): p_categories must contain at least one non-empty value';
  end if;

  create temp table tmp_discount_rolling_30d_snapshots on commit drop as
  with base as (
    select
      v_window_start as window_start,
      v_as_of_date as window_end,
      business_date,
      location_id,
      store_name,
      order_id,
      bill_number,
      receipt_number,
      billed_at,
      paid_at,
      discount_bir_category,
      discount_name_normalized as discount_name,
      full_name_normalized,
      reference_number_normalized,
      customer_name_display,
      reference_number_display,
      discount_amount_total
    from public.v_discount_identity_order_usage
    where business_date between v_window_start and v_as_of_date
      and discount_bir_category = any (v_categories)
  ),
  name_usage as (
    select
      window_start,
      window_end,
      location_id,
      max(store_name) as store_name,
      discount_bir_category,
      max(discount_name) as discount_name,
      full_name_normalized as identity_key,
      array_agg(distinct customer_name_display order by customer_name_display)
        filter (where customer_name_display is not null) as customer_names,
      array_agg(distinct reference_number_display order by reference_number_display)
        filter (where reference_number_display is not null) as reference_numbers,
      array_agg(distinct order_id order by order_id) as order_ids,
      array_agg(distinct bill_number::text order by bill_number::text)
        filter (where bill_number is not null) as bill_numbers,
      array_agg(distinct receipt_number::text order by receipt_number::text)
        filter (where receipt_number is not null) as receipt_numbers,
      array_agg(distinct business_date order by business_date) as business_dates,
      count(distinct order_id)::integer as order_count,
      count(distinct business_date)::integer as active_day_count,
      count(distinct reference_number_normalized)::integer as distinct_counterparty_count,
      min(billed_at) as first_billed_at,
      max(billed_at) as last_billed_at,
      min(paid_at) as first_paid_at,
      max(paid_at) as last_paid_at,
      round(sum(discount_amount_total)::numeric, 2) as discount_amount_total,
      jsonb_build_object(
        'customer_names', to_jsonb(coalesce(array_agg(distinct customer_name_display order by customer_name_display)
          filter (where customer_name_display is not null), array[]::text[])),
        'reference_numbers', to_jsonb(coalesce(array_agg(distinct reference_number_display order by reference_number_display)
          filter (where reference_number_display is not null), array[]::text[])),
        'order_ids', to_jsonb(array_agg(distinct order_id order by order_id)),
        'bill_numbers', to_jsonb(coalesce(array_agg(distinct bill_number::text order by bill_number::text)
          filter (where bill_number is not null), array[]::text[])),
        'receipt_numbers', to_jsonb(coalesce(array_agg(distinct receipt_number::text order by receipt_number::text)
          filter (where receipt_number is not null), array[]::text[])),
        'business_dates', to_jsonb(array_agg(distinct business_date order by business_date)),
        'first_billed_at', min(billed_at),
        'last_billed_at', max(billed_at),
        'first_paid_at', min(paid_at),
        'last_paid_at', max(paid_at)
      ) as details
    from base
    where full_name_normalized is not null
    group by window_start, window_end, location_id, discount_bir_category, full_name_normalized
  ),
  reference_usage as (
    select
      window_start,
      window_end,
      location_id,
      max(store_name) as store_name,
      discount_bir_category,
      max(discount_name) as discount_name,
      reference_number_normalized as identity_key,
      array_agg(distinct customer_name_display order by customer_name_display)
        filter (where customer_name_display is not null) as customer_names,
      array_agg(distinct reference_number_display order by reference_number_display)
        filter (where reference_number_display is not null) as reference_numbers,
      array_agg(distinct order_id order by order_id) as order_ids,
      array_agg(distinct bill_number::text order by bill_number::text)
        filter (where bill_number is not null) as bill_numbers,
      array_agg(distinct receipt_number::text order by receipt_number::text)
        filter (where receipt_number is not null) as receipt_numbers,
      array_agg(distinct business_date order by business_date) as business_dates,
      count(distinct order_id)::integer as order_count,
      count(distinct business_date)::integer as active_day_count,
      count(distinct full_name_normalized)::integer as distinct_counterparty_count,
      min(billed_at) as first_billed_at,
      max(billed_at) as last_billed_at,
      min(paid_at) as first_paid_at,
      max(paid_at) as last_paid_at,
      round(sum(discount_amount_total)::numeric, 2) as discount_amount_total,
      jsonb_build_object(
        'customer_names', to_jsonb(coalesce(array_agg(distinct customer_name_display order by customer_name_display)
          filter (where customer_name_display is not null), array[]::text[])),
        'reference_numbers', to_jsonb(coalesce(array_agg(distinct reference_number_display order by reference_number_display)
          filter (where reference_number_display is not null), array[]::text[])),
        'order_ids', to_jsonb(array_agg(distinct order_id order by order_id)),
        'bill_numbers', to_jsonb(coalesce(array_agg(distinct bill_number::text order by bill_number::text)
          filter (where bill_number is not null), array[]::text[])),
        'receipt_numbers', to_jsonb(coalesce(array_agg(distinct receipt_number::text order by receipt_number::text)
          filter (where receipt_number is not null), array[]::text[])),
        'business_dates', to_jsonb(array_agg(distinct business_date order by business_date)),
        'first_billed_at', min(billed_at),
        'last_billed_at', max(billed_at),
        'first_paid_at', min(paid_at),
        'last_paid_at', max(paid_at)
      ) as details
    from base
    where reference_number_normalized is not null
    group by window_start, window_end, location_id, discount_bir_category, reference_number_normalized
  ),
  computed_alerts as (
    select
      v_as_of_date as as_of_date,
      window_start,
      window_end,
      'store_30d'::text as scope,
      location_id as scope_key,
      location_id,
      store_name,
      discount_name,
      discount_bir_category,
      identity_type,
      identity_key,
      customer_name,
      reference_number,
      order_count,
      active_day_count,
      distinct_counterparty_count,
      'rolling_30d_name_threshold_same_store'::text as detection_type,
      'review'::text as severity,
      details || jsonb_build_object(
        'window_start', window_start,
        'window_end', window_end,
        'active_day_count', active_day_count,
        'distinct_counterparty_count', distinct_counterparty_count,
        'threshold_order_count', p_name_order_threshold,
        'comparison_operator', '>'
      ) as details
    from (
      select
        window_start,
        window_end,
        location_id,
        store_name,
        discount_name,
        discount_bir_category,
        'full_name'::text as identity_type,
        identity_key,
        customer_names[1] as customer_name,
        case when distinct_counterparty_count = 1 then reference_numbers[1] else null end as reference_number,
        order_count,
        active_day_count,
        distinct_counterparty_count,
        details
      from name_usage
    ) usage_base
    where identity_type = 'full_name'
      and order_count > p_name_order_threshold

    union all

    select
      v_as_of_date as as_of_date,
      window_start,
      window_end,
      'store_30d'::text as scope,
      location_id as scope_key,
      location_id,
      store_name,
      discount_name,
      discount_bir_category,
      identity_type,
      identity_key,
      customer_name,
      null::text as reference_number,
      order_count,
      active_day_count,
      distinct_counterparty_count,
      'rolling_30d_name_diff_reference_threshold_same_store'::text as detection_type,
      'high'::text as severity,
      details || jsonb_build_object(
        'window_start', window_start,
        'window_end', window_end,
        'active_day_count', active_day_count,
        'distinct_counterparty_count', distinct_counterparty_count,
        'threshold_order_count', p_name_order_threshold,
        'comparison_operator', '>'
      ) as details
    from (
      select
        window_start,
        window_end,
        location_id,
        store_name,
        discount_name,
        discount_bir_category,
        'full_name'::text as identity_type,
        identity_key,
        customer_names[1] as customer_name,
        order_count,
        active_day_count,
        distinct_counterparty_count,
        details
      from name_usage
    ) usage_base
    where identity_type = 'full_name'
      and order_count > p_name_order_threshold
      and distinct_counterparty_count > 1

    union all

    select
      v_as_of_date as as_of_date,
      window_start,
      window_end,
      'store_30d'::text as scope,
      location_id as scope_key,
      location_id,
      store_name,
      discount_name,
      discount_bir_category,
      identity_type,
      identity_key,
      customer_name,
      reference_number,
      order_count,
      active_day_count,
      distinct_counterparty_count,
      'rolling_30d_reference_threshold_same_store'::text as detection_type,
      'review'::text as severity,
      details || jsonb_build_object(
        'window_start', window_start,
        'window_end', window_end,
        'active_day_count', active_day_count,
        'distinct_counterparty_count', distinct_counterparty_count,
        'threshold_order_count', p_reference_order_threshold,
        'comparison_operator', '>'
      ) as details
    from (
      select
        window_start,
        window_end,
        location_id,
        store_name,
        discount_name,
        discount_bir_category,
        'reference_number'::text as identity_type,
        identity_key,
        case when distinct_counterparty_count = 1 then customer_names[1] else null end as customer_name,
        reference_numbers[1] as reference_number,
        order_count,
        active_day_count,
        distinct_counterparty_count,
        details
      from reference_usage
    ) usage_base
    where identity_type = 'reference_number'
      and order_count > p_reference_order_threshold

    union all

    select
      v_as_of_date as as_of_date,
      window_start,
      window_end,
      'store_30d'::text as scope,
      location_id as scope_key,
      location_id,
      store_name,
      discount_name,
      discount_bir_category,
      identity_type,
      identity_key,
      null::text as customer_name,
      reference_number,
      order_count,
      active_day_count,
      distinct_counterparty_count,
      'rolling_30d_reference_diff_name_threshold_same_store'::text as detection_type,
      'high'::text as severity,
      details || jsonb_build_object(
        'window_start', window_start,
        'window_end', window_end,
        'active_day_count', active_day_count,
        'distinct_counterparty_count', distinct_counterparty_count,
        'threshold_order_count', p_reference_order_threshold,
        'comparison_operator', '>'
      ) as details
    from (
      select
        window_start,
        window_end,
        location_id,
        store_name,
        discount_name,
        discount_bir_category,
        'reference_number'::text as identity_type,
        identity_key,
        reference_numbers[1] as reference_number,
        order_count,
        active_day_count,
        distinct_counterparty_count,
        details
      from reference_usage
    ) usage_base
    where identity_type = 'reference_number'
      and order_count > p_reference_order_threshold
      and distinct_counterparty_count > 1
  )
  select *
  from computed_alerts;

  delete from public.discount_identity_30d_snapshots existing
  where existing.as_of_date = v_as_of_date
    and existing.detection_type = any (v_detection_types)
    and existing.discount_bir_category = any (v_categories)
    and not exists (
      select 1
      from tmp_discount_rolling_30d_snapshots fresh
      where fresh.as_of_date = existing.as_of_date
        and fresh.scope = existing.scope
        and fresh.scope_key = existing.scope_key
        and fresh.discount_bir_category = existing.discount_bir_category
        and fresh.identity_type = existing.identity_type
        and fresh.identity_key = existing.identity_key
        and fresh.detection_type = existing.detection_type
    );

  insert into public.discount_identity_30d_snapshots (
    as_of_date,
    window_start,
    window_end,
    scope,
    scope_key,
    location_id,
    store_name,
    discount_name,
    discount_bir_category,
    identity_type,
    identity_key,
    customer_name,
    reference_number,
    order_count,
    active_day_count,
    distinct_counterparty_count,
    detection_type,
    severity,
    details,
    created_at,
    updated_at
  )
  select
    as_of_date,
    window_start,
    window_end,
    scope,
    scope_key,
    location_id,
    store_name,
    discount_name,
    discount_bir_category,
    identity_type,
    identity_key,
    customer_name,
    reference_number,
    order_count,
    active_day_count,
    distinct_counterparty_count,
    detection_type,
    severity,
    details,
    now() as created_at,
    now() as updated_at
  from tmp_discount_rolling_30d_snapshots
  on conflict (
    as_of_date,
    scope,
    scope_key,
    discount_bir_category,
    identity_type,
    identity_key,
    detection_type
  )
  do update
    set location_id = excluded.location_id,
        store_name = excluded.store_name,
        discount_name = excluded.discount_name,
        customer_name = excluded.customer_name,
        reference_number = excluded.reference_number,
        window_start = excluded.window_start,
        window_end = excluded.window_end,
        order_count = excluded.order_count,
        active_day_count = excluded.active_day_count,
        distinct_counterparty_count = excluded.distinct_counterparty_count,
        severity = excluded.severity,
        details = excluded.details,
        updated_at = now();

  select count(*)
    into v_alert_count
  from tmp_discount_rolling_30d_snapshots;

  return v_alert_count;
end;
$$;

comment on view public.v_discount_identity_order_usage is
  'One row per paid order/category/name/reference combination for same-day Senior Citizen/PWD identity analysis.';

comment on function public.refresh_discount_identity_alerts(date, text[]) is
  'Refresh same-day Senior Citizen/PWD identity alerts into discount_abuse_alerts. Use after POS sync or via pg_cron.';

comment on view public.v_discount_identity_rolling_30d_usage is
  'Rolling 30-day per-store Senior Citizen/PWD identity usage for names and reference numbers, anchored on current_date.';

comment on function public.refresh_discount_rolling_30d_identity_alerts(date, text[], integer, integer) is
  'Refresh rolling 30-day per-store Senior Citizen/PWD identity threshold snapshots into discount_identity_30d_snapshots.';

comment on table public.discount_identity_30d_snapshots is
  'Rolling 30-day same-store identity review snapshots for Senior Citizen/PWD discount monitoring.';
